UNICODE_STRING STRUCT
	_Length WORD 0
	MaximumLength WORD 0
	Buffer DWORD 0
UNICODE_STRING ENDS
CRITICAL_SECTION STRUCT
	PTR1 DWORD 0
	PTR2 DWORD 0
	PTR3 DWORD 0
	PTR4 DWORD 0
	CNT1 DWORD 0
	CNT2 DWORD 0
	HNDL DWORD 0
CRITICAL_SECTION ENDS

EXTERN SYSCALL  ?InstructionDP3@PixelShaderAssembler@XGRAPHICS@@AAEXKKPAK00000@Z :PROC
EXTERN SYSCALL  ?InstructionLRP@XGRAPHICS@@YGXKKPAK00000@Z :PROC

EXTERN SYSCALL ?debugPrintString@@3PADA : DWORD
EXTERN SYSCALL ?debugPrintValue@@3HA : DWORD
EXTERN SYSCALL ?debugPrintValueFloat@@3MA : DWORD
EXTERN SYSCALL ?debugPrintValueArrayCnt@@3HA : DWORD
EXTERN SYSCALL ?_this@@3PAXA : DWORD
EXTERN SYSCALL ?EBP@@3PAXA : DWORD
EXTERN SYSCALL ?ESP@@3PAXA : DWORD
EXTERN SYSCALL ?RegisterFunction@@YGXXZ : PROC
EXTERN SYSCALL ?DbgPrintStr@@YGXXZ : PROC
EXTERN SYSCALL ?DbgPrintValue@@YGXXZ : PROC
EXTERN SYSCALL ?DbgPrintValueFloat@@YGXXZ : PROC
EXTERN SYSCALL ?DbgPrintValueFloatArray@@YGXXZ : PROC
EXTERN SYSCALL ?PrintThisInfo@@YGXXZ : PROC
EXTERN SYSCALL ?Backtrace@@YGXXZ : PROC
EXTERN SYSCALL ?DbgInit@@YGXXZ : PROC
EXTERN SYSCALL ?thunk@@YADHHH@Z : PROC
EXTERN __security_cookie : DWORD
