IFDEF DEBUG_ENABLED

EXTERN SYSCALL ?debugPrintString@@3PADA : DWORD
EXTERN SYSCALL ?debugPrintValue@@3HA : DWORD
EXTERN SYSCALL ?debugFPUStatus@@3HA : DWORD
EXTERN SYSCALL ?debugPrintValueFloat@@3MA : DWORD
EXTERN SYSCALL ?debugPrintValueArrayCnt@@3HA : DWORD
EXTERN SYSCALL ?_this@@3PAXA : DWORD
EXTERN SYSCALL ?EBP@@3PAXA : DWORD
EXTERN SYSCALL ?ESP@@3PAXA : DWORD

EXTERN SYSCALL ?DbgInit@@YGXXZ : PROC

EXTERN SYSCALL ?DbgPrintValue@@YGXXZ : PROC
EXTERN SYSCALL ?DbgPrintValueFloat@@YGXXZ : PROC
EXTERN SYSCALL ?DbgPrintValueFloatArray@@YGXXZ : PROC
EXTERN SYSCALL ?DbgPrintStr@@YGXXZ : PROC

EXTERN SYSCALL ?RegisterFunction@@YGXXZ : PROC
EXTERN SYSCALL ?PrintThisInfo@@YGXXZ : PROC
EXTERN SYSCALL ?Backtrace@@YGXXZ : PROC
EXTERN SYSCALL ?CheckFPUState@@YGXXZ : PROC

ENDIF