IFDEF DEBUG_ENABLED

EXTERN SYSCALL ?debugPrintString@@3PADA : DWORD
EXTERN SYSCALL ?debugCurrentFunction@@3PADA : DWORD
EXTERN SYSCALL ?debugPrintValue@@3HA : DWORD
EXTERN SYSCALL ?debugFPUStatus@@3HA : DWORD
EXTERN SYSCALL ?debugPrintValueFloat@@3MA : DWORD
EXTERN SYSCALL ?debugPrintValueArrayCnt@@3HA : DWORD
EXTERN SYSCALL ?_this@@3PAXA : DWORD
EXTERN SYSCALL ?EBP@@3PAXA : DWORD
EXTERN SYSCALL ?ESP@@3PAXA : DWORD

EXTERN SYSCALL ?DbgInit@@YGXXZ : PROC

EXTERN SYSCALL ?DbgPrintValue@@YGXXZ : PROC
EXTERN SYSCALL ?DbgCalllog@@YGXXZ : PROC
EXTERN SYSCALL ?DbgPrintValueFloat@@YGXXZ : PROC
EXTERN SYSCALL ?DbgPrintValueFloatArray@@YGXXZ : PROC
EXTERN SYSCALL ?DbgPrintStr@@YGXXZ : PROC

EXTERN SYSCALL ?RegisterFunction@@YGXXZ : PROC
EXTERN SYSCALL ?PrintThisInfo@@YGXXZ : PROC
EXTERN SYSCALL ?Backtrace@@YGXXZ : PROC
EXTERN SYSCALL ?CheckFPUState@@YGXXZ : PROC

DEBUG_PROLOGUE_MACRO MACRO
	PUSHA
	PUSHFD
	FXSAVE [DBG_FPU_STATE]
ENDM

DEBUG_HEADER_MACRO MACRO
	IFDEF DEBUG_CALLLOG
	CALL DBG_CALLLOG
	ENDIF
	
	IFDEF DEBUG_REG_FUNC
	CALL DBG_REGISTER_FUNCTION
	ENDIF
	
	IFDEF DEBUG_FPU_MONITOR
	CALL DBG_CHECK_FPU_STATE
	ENDIF
ENDM

DEBUG_HEADER_THISCALL_MACRO MACRO
	PUSH ECX
	IFDEF DEBUG_CALLLOG
	CALL DBG_CALLLOG
	ENDIF
	
	IFDEF DEBUG_REG_FUNC
	CALL DBG_REGISTER_FUNCTION
	ENDIF
	
	IFDEF DEBUG_FPU_MONITOR
	CALL DBG_CHECK_FPU_STATE
	ENDIF
	POP ECX
	
	IFDEF DEBUG_THIS_PRINT
	MOV EAX, [ECX]
	MOV [?_this@@3PAXA], EAX
	CALL DBG_PRINT_THIS
	ENDIF
ENDM

DEBUG_EPILOGUE_MACRO MACRO
	FXRSTOR [DBG_FPU_STATE]
	POPFD
	POPA
ENDM

ENDIF