IFDEF DEBUG_ENABLED

DBG_REGISTER_FUNCTION PROC
	MOV [?ESP@@3PAXA], ESP
	CALL ?RegisterFunction@@YGXXZ
	RET
DBG_REGISTER_FUNCTION ENDP

DBG_INIT PROC
	MOV [?EBP@@3PAXA], EBP
	CALL ?DbgInit@@YGXXZ
	RET
DBG_INIT ENDP

DBG_PRINT PROC
	CALL ?DbgPrintStr@@YGXXZ
	RET
DBG_PRINT ENDP

DBG_CALLLOG PROC
	CALL ?DbgCalllog@@YGXXZ
	RET
DBG_CALLLOG ENDP

DBG_PRINT_VALUE PROC
	CALL ?DbgPrintValue@@YGXXZ
	RET
DBG_PRINT_VALUE ENDP

DBG_PRINT_VALUE_FLOAT PROC
	CALL ?DbgPrintValueFloat@@YGXXZ
	RET
DBG_PRINT_VALUE_FLOAT ENDP

DBG_PRINT_VALUE_FLOAT_ARRAY PROC
	CALL ?DbgPrintValueFloatArray@@YGXXZ
	RET
DBG_PRINT_VALUE_FLOAT_ARRAY ENDP

DBG_PRINT_THIS PROC
	CALL ?PrintThisInfo@@YGXXZ
	RET
DBG_PRINT_THIS ENDP

DBG_BACKTRACE PROC
	MOV [?ESP@@3PAXA], ESP
	CALL ?Backtrace@@YGXXZ
	RET
DBG_BACKTRACE ENDP

DBG_PRINT_FPU_STATE PROC
	XOR EAX, EAX
	FSTSW AX
	AND AX, 3Fh
	MOV dword ptr [?debugPrintValue@@3HA], EAX
	MOV EAX, OFFSET DBG_FSTATUS
	MOV [?debugPrintString@@3PADA], EAX
	CALL ?DbgPrintValue@@YGXXZ
	RET
DBG_PRINT_FPU_STATE ENDP

DBG_SAVE_FPU_STATE PROC
	XOR EAX, EAX
	FSTSW AX
	AND AX, 3Fh
	MOV dword ptr [?debugFPUStatus@@3HA], EAX
	RET
DBG_SAVE_FPU_STATE ENDP

DBG_CHECK_FPU_STATE PROC
	XOR EAX, EAX
	FSTSW AX
	AND AX, 3Fh
	MOV dword ptr [?debugFPUStatus@@3HA], EAX
	CALL ?CheckFPUState@@YGXXZ
	RET
DBG_CHECK_FPU_STATE ENDP

ENDIF