#pragma once
#include <twin_base.h>
#include "percept_abstract.h"

REGISTER_PERCEPT(Next)
REGISTER_PERCEPT(IsCollidable)
REGISTER_PERCEPT(Else)
REGISTER_PERCEPT(Random)
REGISTER_PERCEPT(IsVisible)
REGISTER_PERCEPT(TimeInUnit)
REGISTER_PERCEPT(AttachedToAnAgent)
REGISTER_PERCEPT(SqrMoveSpeed)
REGISTER_PERCEPT(IsBusy)
REGISTER_PERCEPT(FocusIsBusy)
REGISTER_PERCEPT(0x04D)
REGISTER_PERCEPT(0x04E)
REGISTER_PERCEPT(0x04F)
REGISTER_PERCEPT(0x050)
REGISTER_PERCEPT(0x051)
REGISTER_PERCEPT(0x052)
REGISTER_PERCEPT(0x053)
REGISTER_PERCEPT(0x054)
REGISTER_PERCEPT(0x055)
REGISTER_PERCEPT(0x056)